### ISSUE TITLE
On logging in, logging out again, invalid credentials

### ISSUE THREAD

**Issue by anubhabsen** [felicity-buzz-2k16/quiz-portal-frontend#5]
Log in once, log out, and click log in in the nav bar. Credentials are auto typed so that you don't have to type it again, but clicking log in shows invalid credentials. Re typing the email and password manually solves the issue.

**Comment by meghprkh** [comment]
Yes, I know this. Mostly it is preact bug caused by linkState and browser not emitting onInputChange second time. Still I will try to find a solution.
